Repository typedb/typedb-docs, pull requests merged in 2019-08, with the labels that each got.

#203 Updates `grakn console` options
  02-running-grakn/02-console.md
Labels: bug

#204 Add java regex link to match using like clause
  11-query/01-match-clause.md
Labels: refactor

#205 Update License to 2019
  .circleci/config.yml
  WORKSPACE
  dependencies/graknlabs/BUILD
  dependencies/graknlabs/dependencies.bzl
  dependencies/maven/update.sh
  test/conf/grakn.properties
Labels: refactor

#206 License update 2019
  dependencies/graknlabs/dependencies.bzl
Labels: refactor

#207 Add Soroush as the code owner
  .github/CODEOWNERS
Labels: build
