Repository typedb/typedb-docs, pull requests merged in 2019-09, with the labels that each got.

#210 Add example for graql rule retrieval
  09-schema/03-rules.md
Labels: bug, refactor

#212 Use grakn.properties from @graknlabs_grakn_core
  test/conf/BUILD
  test/conf/grakn.properties
  test/example/java/BUILD
  test/example/nodejs/BUILD
  test/example/nodejs/PhoneCalls.template.js
  test/query/BUILD
  test/query/graql-java-tests.py
  test/query/graql-lang-tests.py
Labels: bug

#213 Remove `Important` and Read-only workbase comments
  07-workbase/00-overview.md
Labels: refactor

#214 Ensures `phone_calls` nodejs query examples run on a keyspace with no data
  test/example/nodejs/PhoneCalls.template.js
Labels: bug

#217 Fix CI
  test/example/java/BUILD
  test/example/java/java_tests.py
  test/example/nodejs/BUILD
  test/example/nodejs/nodejs_tests.py
  test/example/python/BUILD
  test/example/python/python_tests.py
  test/links/BUILD
  test/links/links_test.py
  test/links/requirements.txt
Labels: bug, build
