Repository typedb/typedb-docs, pull requests merged in 2019-04, with the labels that each got.

#127 Update instructions for installing/downloading with docker and mac (on master)
  00-general/04-quickstart.md
  02-running-grakn/01-install-and-run.md
Labels: refactor

#130 complete and improve the readme
  README.md
  test/example/README.md
  test/query/README.md
Labels: refactor

#132 Fix typos in images
  images/query/example-pattern.png
  images/schema/unstructured-problems.png
  images/source/query/example-pattern.sketch
  images/source/schema/unstructured-problems.sketch
Labels: bug, refactor

#135 correct the download paths for social-network data and schema
  00-general/04-quickstart.md
Labels: bug

#134 Customise generic instructions as per OS
  02-running-grakn/01-install-and-run.md
Labels: refactor

#143 Changes artifact-id of Client Java to api
  03-client-api/01-java.md
Labels: bug

#144 Changes client python package name to grakn-client
  03-client-api/02-python.md
Labels: bug

#145 Correct client nodejs package name and client python import instruction
  03-client-api/02-python.md
  03-client-api/03-nodejs.md
Labels: bug

#146 Adds a missing backtick
  11-query/07-compute-query.md
Labels: bug

#147 adds/updates docs on sub, sub! and type
  11-query/01-match-clause.md
Labels: feature, refactor

#148 update explanation on aggreagte count
  11-query/06-aggregate-query.md
Labels: bug, refactor

#154 Compatibility matrix for Workbase
  07-workbase/00-overview.md
Labels: workbase

#156 Guide to writing your own Client
  03-client-api/00-overview.md
  03-client-api/04-new-client.md
  test/example/python/BUILD
  test/example/python/social_network_test.py
  views/sidebar.yml
Labels: feature

#162 Clarify wording on iterator
  03-client-api/references/iterator.yml
Labels: refactor

#163 Add `ConceptMap.get(var)` to docs
  03-client-api/references/answer.yml
Labels: feature

#164 Fixes broken links in Client/Concept API References
  03-client-api/references/answer.yml
  03-client-api/references/graql.yml
  03-client-api/references/iterator.yml
  03-client-api/references/transaction.yml
  04-concept-api/02-type.md
  04-concept-api/references/attribute.yml
  04-concept-api/references/attribute_type.yml
  04-concept-api/references/concept.yml
  04-concept-api/references/relation.yml
  04-concept-api/references/relation_type.yml
  04-concept-api/references/role.yml
  04-concept-api/references/rule.yml
  04-concept-api/references/thing.yml
  04-concept-api/references/type.yml
  06-management/01-keyspace.md
  test/links/links_test.py
  views/autolink-keywords.js
Labels: bug

#166 Updating data - typo
  11-query/05-updating-data.md
Labels: bug
