Repository typedb/typedb-docs, pull requests merged in 2019-03, with the labels that each got.

#53 Add grabl-marker for autoupdating
  WORKSPACE
Labels: build

#54 update/improve client api references+ quickstart examples
  03-client-api/01-java.md
  03-client-api/02-python.md
  03-client-api/03-nodejs.md
  03-client-api/references/answer.yml
  03-client-api/references/client.yml
  03-client-api/references/grakn.yml
  03-client-api/references/graql.yml
  03-client-api/references/iterator.yml
  03-client-api/references/session.yml
  03-client-api/references/transaction.yml
  views/autolink-keywords.js
Labels: refactor

#55 update branch classification and pr instructions in readme
  README.md
Labels: refactor

#56 client-java as direct dep, client-python as git dep
  00-general/04-quickstart.md
  03-client-api/01-java.md
  08-examples/03-migration-java.md
  08-examples/06-queries.md
  WORKSPACE
  test/snippet/BUILD
  test/snippet/generate-test-snippet-graql.py
  test/snippet/generate-test-snippet-java.py
  test/standalone/java/BUILD
  test/standalone/java/PhoneCalls.java
  test/standalone/java/SocialNetwork.java
  test/standalone/python/BUILD
  test/standalone/python/social_network.py
Labels: refactor

#61 organise WORKSPACE and add graql as a transitive dependency
  WORKSPACE
  dependencies/tools/dependencies.bzl
Labels: refactor

#60 updates/improve concept-api
  04-concept-api/01-concept.md
  04-concept-api/02-type.md
  04-concept-api/04-thing.md
  04-concept-api/references/attribute.yml
  04-concept-api/references/attribute_type.yml
  04-concept-api/references/concept.yml
  04-concept-api/references/entity_type.yml
  04-concept-api/references/relationship.yml
  04-concept-api/references/relationship_type.yml
  04-concept-api/references/role.yml
  04-concept-api/references/rule.yml
  04-concept-api/references/thing.yml
  04-concept-api/references/type.yml
Labels: refactor

#59 Update java migration tutorials
  08-examples/03-migration-java.md
  08-examples/06-queries.md
Labels: refactor

#62 find-replace all relationships to relation, except schema.gql files
  00-general/04-quickstart.md
  03-client-api/references/transaction.yml
  04-concept-api/00-overview.md
  04-concept-api/02-type.md
  04-concept-api/04-thing.md
  04-concept-api/references/relation.yml
  04-concept-api/references/relation_type.yml
  04-concept-api/references/role.yml
  04-concept-api/references/thing.yml
  04-concept-api/references/type.yml
  07-workbase/02-visualising.md
  07-workbase/03-investigating.md
  08-examples/02-schema.md
  08-examples/migration-notes.md
  09-schema/00-overview.md
  09-schema/01-concepts.md
  09-schema/03-rules.md
  10-query/01-match-clause.md
  10-query/03-insert-query.md
  10-query/04-delete-query.md
  10-query/05-updating-data.md
  10-query/07-compute-query.md
Labels: refactor

#64 Extends ci workflow
  .circleci/config.yml
  .circleci/deploy-docs.py
  10-query/01-match-clause.md
Labels: refactor

#65 add bazelrc for rbe support
  .bazelrc
Labels: feature

#66 adds bazel-toolchain as a tool dependency
  dependencies/tools/dependencies.bzl
Labels: bug

#68 fixes broken links in query/overview
  10-query/00-overview.md
Labels: bug

#69 fixes broken links in query/overview
  10-query/00-overview.md
Labels: bug

#67 break the test job into smaller ones
  .circleci/config.yml
  test/standalone/java/PhoneCalls.java
  test/standalone/java/SocialNetwork.java
  test/standalone/python/BUILD
Labels: refactor

#71 update deploy-docs.py to handle dynamic branch input
  .circleci/deploy-docs.py
Labels: refactor

#72 Replaced common build tools dependencies with @graknlabs_build_tools
  .circleci/config.yml
  WORKSPACE
  dependencies/tools/BUILD
  dependencies/tools/dependencies.bzl
Labels: build, refactor

#73 Added .ijwb/ and bazel-* to .gitignore
  .gitignore
Labels: build

#74 Update maven artifacts
  dependencies/maven/artifacts/junit/BUILD
  dependencies/maven/artifacts/org/hamcrest/BUILD
  dependencies/maven/artifacts/org/sharegov/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/update.sh
Labels: build

#81 Rename grakn-core-all-linux.tar.gz
  .circleci/config.yml
Labels: bug, build

#84 Updates for new clients
  00-general/04-quickstart.md
  03-client-api/02-python.md
  03-client-api/03-nodejs.md
  03-client-api/references/client.yml
  03-client-api/references/grakn.yml
  03-client-api/references/session.yml
  08-examples/03-migration-java.md
  08-examples/04-migration-nodejs.md
  08-examples/05-migration-python.md
  08-examples/06-queries.md
  test/example/nodejs/PhoneCalls.template.js
  test/example/nodejs/SocialNetwork.template.js
  test/example/nodejs/package.json
  test/example/python/BUILD
  test/example/python/phone_calls_test.py
  test/example/python/social_network_test.py
Labels: refactor

#87 Remove client pypi dep
  test/example/nodejs/package.json
  test/example/python/BUILD
  test/example/python/requirements.txt
Labels: refactor

#91 correct the update example
  10-query/05-updating-data.md
Labels: bug

#89 fix yml structural error
  03-client-api/references/client.yml
Labels: bug

#94 Add meta keywords and summary for each page
  00-general/04-quickstart.md
  02-running-grakn/01-install-and-run.md
  02-running-grakn/02-console.md
  02-running-grakn/03-configuration.md
  03-client-api/00-overview.md
  03-client-api/01-java.md
  03-client-api/02-python.md
  03-client-api/03-nodejs.md
  04-concept-api/00-overview.md
  04-concept-api/01-concept.md
  04-concept-api/02-type.md
  04-concept-api/03-rule.md
  04-concept-api/04-thing.md
  05-cloud-deployment/01-kgms.md
  05-cloud-deployment/02-google-cloud.md
  05-cloud-deployment/03-aws.md
  06-management/01-keyspace.md
  06-management/02-users.md
  07-workbase/00-overview.md
  07-workbase/01-preferences.md
  07-workbase/02-visualising.md
  07-workbase/03-investigating.md
  07-workbase/04-schema-designer.md
  08-examples/01-overview.md
  08-examples/02-schema.md
  08-examples/03-migration-java.md
  08-examples/04-migration-nodejs.md
  08-examples/05-migration-python.md
  08-examples/06-queries.md
  09-schema/00-overview.md
  09-schema/01-concepts.md
  09-schema/03-rules.md
  10-query/00-overview.md
  10-query/01-match-clause.md
  10-query/02-get-query.md
  10-query/03-insert-query.md
  10-query/04-delete-query.md
  10-query/05-updating-data.md
  10-query/06-aggregate-query.md
  10-query/07-compute-query.md
Labels: feature

#102 rename parab lang to tab
  04-concept-api/02-type.md
  04-concept-api/references/attribute.yml
  04-concept-api/references/attribute_type.yml
  04-concept-api/references/concept.yml
  04-concept-api/references/relation.yml
  04-concept-api/references/relation_type.yml
  04-concept-api/references/role.yml
  04-concept-api/references/thing.yml
  04-concept-api/references/type.yml
  08-examples/03-migration-java.md
  08-examples/04-migration-nodejs.md
  08-examples/05-migration-python.md
Labels: refactor

#100 use unique values for office registration-number
  files/social-network/data.gql
Labels: bug

#105 Fix typos
  00-general/04-quickstart.md
Labels: bug

#104 fix typos
  00-general/04-quickstart.md
  10-query/00-overview.md
Labels: bug

#108 Add benchmark as transitive dependency
  WORKSPACE
Labels: bug

#107 Graql overview revision
  10-query/00-overview.md
  images/query/query-structure.png
  images/source/query/example-pattern-graql.key
  images/source/query/query-structure.sketch
Labels: refactor

#114 Fix mistype in phone calls nodejs migration snippet
  08-examples/04-migration-nodejs.md
Labels: bug

#113 Fix mistype in phone calls nodejs migration snippet
  08-examples/03-phone-calls-migration-nodejs.md
Labels: bug

#115 Install -all package; import APT key before adding repo
  02-running-grakn/01-install-and-run.md
Labels: build

#116 Update quickstart
  00-general/04-quickstart.md
Labels: refactor

#117 Adds docker to install keywords
  02-running-grakn/01-install-and-run.md
Labels: refactor

#118 Updates configuration content
  02-running-grakn/01-install-and-run.md
  02-running-grakn/03-configuration.md
Labels: refactor

#119 Update clients
  03-client-api/00-overview.md
  03-client-api/01-java.md
Labels: refactor

#120 Updates concept api content
  04-concept-api/00-overview.md
Labels: refactor

#121 Update users
  06-management/02-users.md
Labels: refactor

#123 Update query etc
  08-examples/01-phone-calls-schema.md
  09-schema/01-concepts.md
  09-schema/03-rules.md
  10-query/01-match-clause.md
  10-query/02-get-query.md
  10-query/03-insert-query.md
  10-query/04-delete-query.md
  10-query/05-updating-data.md
  10-query/06-aggregate-query.md
  10-query/07-compute-query.md
Labels: refactor

#122 Update schema
  09-schema/00-overview.md
  09-schema/01-concepts.md
Labels: refactor

#125 Resolve rules failing tests
  09-schema/03-rules.md
Labels: refactor
