Repository typedb/typedb-docs, pull requests merged in 2019-11, with the labels that each got.

#233 Documents the `isOpen()` for Client Node.js
  03-client-api/references/answer.yml
  03-client-api/references/transaction.yml
  test/example/nodejs/yarn.lock
  views/autolink-keywords.js
Labels: feature

#237 Bump dependencies
  dependencies/graknlabs/dependencies.bzl
  test/example/nodejs/package.json
Labels: build

#240 Updates the list of reserved keywords
  09-schema/00-overview.md
Labels: refactor

#235 Documents isOpen/is_Open for Clients Java and Python + Void Answer Type
  03-client-api/references/answer.yml
  03-client-api/references/transaction.yml
Labels: feature

#232 Add `delete` and `isDeleted` to Concept API docs
  04-concept-api/references/concept.yml
Labels: refactor

#238 Retrievable Explanation Doc updates
  03-client-api/01-java.md
  03-client-api/02-python.md
  03-client-api/03-nodejs.md
  03-client-api/references/answer.yml
  views/autolink-keywords.js
Labels: refactor

#242 Fix issue with example 5 query list index in Python version
  08-examples/05-phone-calls-queries.md
Labels: bug

#244 Update query examples for the "Owners with attributes of given values" section
  11-query/01-match-clause.md
Labels: bug
