Repository typedb/typedb-docs, pull requests merged in 2020-04, with the labels that each got.

#282 Pin the version of @bazel/jasmine at compatible 0.33.1
  test/example/nodejs/package.json
  test/example/nodejs/yarn.lock
Labels: priority: blocker, type: bug

#289 Mention 1.6.1 compatibility
  03-client-api/02-python.md
  03-client-api/references/iterator.yml
  08-examples/05-phone-calls-queries.md
  views/autolink-keywords.js
Labels: priority: medium, type: documentation

#295 Fixes dependency issues
  dependencies/graknlabs/dependencies.bzl
Labels: type: bug

#294 Resolves `plays` validation errors in the `social_network` schema
  files/social-network/schema.gql
Labels: type: bug

#297 Fix example rule that wouldn't pass validation
  09-schema/03-rules.md
Labels: type: bug
