Repository typedb/typedb-docs, pull requests merged in 2020-07, with the labels that each got.

#317 Fixes the download links in .circleci/config
  .circleci/config.yml
Labels: type: build

#320 Update graknlabs dependencies and depend on Grakn artifact for tests
  .circleci/config.yml
  BUILD
  WORKSPACE
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/artifacts.bzl
  dependencies/maven/artifacts.snapshot
  dependencies/maven/artifacts/com/google/code/gson/BUILD
  dependencies/maven/artifacts/com/univocity/BUILD
  dependencies/maven/artifacts/commons-io/BUILD
  dependencies/maven/artifacts/javax/xml/stream/BUILD
  dependencies/maven/artifacts/junit/BUILD
  dependencies/maven/artifacts/org/hamcrest/BUILD
  dependencies/maven/artifacts/org/sharegov/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
  dependencies/maven/update.sh
  test/example/java/BUILD
  test/query/BUILD
  test/query/graql-java-tests.py
  test/query/graql-lang-tests.py
  test/query/templates/GraqlJavaTest.java
  test/query/templates/GraqlLangTest.java
Labels: priority: high, type: build

#323 Update rules section of the docs
  09-schema/03-rules.md
Labels: type: documentation
