Repository typedb/typedb-docs, pull requests merged in 2020-09, with the labels that each got.

#330 Clarify best practices
  03-client-api/00-overview.md
Labels: priority: high, type: documentation

#328 Fixes a typo
  03-client-api/references/graql.yml
Labels: type: bug

#338 Fix note in concept API overview
  04-concept-api/00-overview.md
Labels: type: bug

#339 Update compatibility table for 1.8.3 grakn core
  03-client-api/01-java.md
Labels: priority: high
