Repository typedb/typedb-docs, pull requests merged in 2021-11, with the labels that each got.

#569 Add "asRemote" to Remote Concept API code examples
  04-concept-api/references/attribute.yml
  04-concept-api/references/attribute_type.yml
  04-concept-api/references/boolean_attribute_type.yml
  04-concept-api/references/concept.yml
  04-concept-api/references/datetime_attribute_type.yml
  04-concept-api/references/double_attribute_type.yml
  04-concept-api/references/entity_type.yml
  04-concept-api/references/long_attribute_type.yml
  04-concept-api/references/relation.yml
  04-concept-api/references/relation_type.yml
  04-concept-api/references/role_type.yml
  04-concept-api/references/rule.yml
  04-concept-api/references/string_attribute_type.yml
  04-concept-api/references/thing.yml
  04-concept-api/references/thing_type.yml
  04-concept-api/references/type.yml
Labels: priority: medium, type: documentation

#578 TypeDB Cluster Kubernetes docs: external hostnames
  05-running-typedb-cluster/02-kubernetes.md
Labels: priority: high, type: documentation

#575 Explain best practice when providing addresses to TypeDB Cluster client
  03-client-api/references/typedb.yml
Labels: priority: medium, type: documentation

#579 Indicate that getPlayers takes in a list of roles
  04-concept-api/references/relation.yml
Labels: type: bug, priority: high
