Repository typedb/typedb-docs, pull requests merged in 2021-09, with the labels that each got.

#556 Document logging into Logstash
  01-running-typedb/03-configuration.md
  05-running-typedb-cluster/02-kubernetes-deployment.md
Labels: type: build, priority: high, type: documentation

#561 Create introduction page
  .grabl/automation.yml
  00-general/03-introduction.md
  00-general/04-quickstart.md
  11-query/02-get-query.md
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  test/example/nodejs/package.json
  test/example/nodejs/yarn.lock
  test/query/templates/TypeQLJavaTest.java
  views/sidebar.yml
Labels: priority: blocker, type: documentation

#562 Update visualisation image in quickstart
  00-general/04-quickstart.md
  images/quickstart/studio-risky-bank.png
  images/quickstart/workbase_sample_query.png
Labels: priority: high, type: documentation
