Repository typedb/typedb-docs, pull requests merged in 2021-08, with the labels that each got.

#552 Fix invalid invocations of Helm commands
  05-typedb-cluster/02-kubernetes.md
Labels: type: bug, priority: blocker, type: documentation

#554 Describe how to configure Logback in client-java
  03-client-api/01-java.md
Labels: type: feature, priority: medium

#555 Restructure Kubernetes deployment for clarity
  05-typedb-cluster/02-kubernetes-deployment.md
Labels: priority: high
