Repository typedb/typedb-docs, pull requests merged in 2021-05, with the labels that each got.

#518 Rename GRAKN env vars in Grabl CI to VATICLE
  .grabl/automation.yml
Labels: priority: high, type: build

#519 Add LogicManager API docs for Python
  04-concept-api/03-rule.md
Labels: priority: medium, type: bug

#523 Document encryption for Helm package
  05-typedb-cluster/02-kubernetes.md
Labels: priority: high

#525 Undefining a relation automatically undefines its roles
  09-schema/01-concepts.md
Labels: priority: low
