Repository typedb/typedb-docs, pull requests merged in 2021-02, with the labels that each got.

#488 Fix update links
  09-schema/00-overview.md
  11-query/04-delete-query.md
  11-query/05-update-query.md
  views/sidebar.yml
Labels: priority: medium, type: bug

#489 Repair Hanging Tests
  09-schema/01-concepts.md
  10-pattern/01-negation.md
  11-query/03-insert-query.md
  11-query/05-update-query.md
  dependencies/graknlabs/repositories.bzl
  test/query/graql-java-tests.py
  test/query/graql-lang-tests.py
  test/query/templates/GraqlJavaTest.java
  test/query/templates/GraqlLangTest.java
Labels: priority: blocker, type: bug

#494 Clean up Rules section and note valid rule forms
  09-schema/03-rules.md
  dependencies/graknlabs/artifacts.bzl
Labels: priority: high, type: documentation
