Repository typedb/typedb-docs, pull requests merged in 2021-07, with the labels that each got.

#530 Put back negation rules
  .grabl/automation.yml
  09-schema/01-concepts.md
  files/social-network/schema.tql
Labels: priority: high, type: bug

#537 Fix URL in the graph DBs vs TypeDB comparison page
  12-comparisons/02-graph-databases-and-typedb.md
Labels: priority: high

#536 File path updates for images
  12-comparisons/02-graph-databases-and-typedb.md
  images/comparisons/typedb-abstraction-over-graph.png
Labels: priority: high, type: bug

#542 Fix an outdated example of loading a schema
  09-schema/00-overview.md
Labels: type: bug, type: documentation

#543 Address issues in docs
  04-concept-api/references/attribute.yml
  06-management/04-migration-and-backup.md
  08-examples/03-phone-calls-migration-nodejs.md
  08-examples/05-phone-calls-queries.md
  09-schema/00-overview.md
  09-schema/01-concepts.md
  09-schema/03-rules.md
  10-pattern/00-overview.md
  10-pattern/01-negation.md
  11-query/01-match-clause.md
  11-query/02-get-query.md
  11-query/03-insert-query.md
  11-query/04-delete-query.md
  11-query/06-aggregate-query.md
  12-comparisons/00-sql-and-typeql.md
  12-comparisons/01-semantic-web-and-typedb.md
  files/social-network/data.tql
  files/social-network/schema.tql
Labels: priority: high, type: bug, type: documentation

#544 Update NodeJS docs to use new property getters
  .grabl/automation.yml
  00-general/04-quickstart.md
  03-client-api/01-java.md
  03-client-api/02-python.md
  03-client-api/03-nodejs.md
  03-client-api/references/answer.yml
  03-client-api/references/client.yml
  03-client-api/references/query_manager.yml
  03-client-api/references/session.yml
  03-client-api/references/transaction.yml
  04-concept-api/references/attribute.yml
  04-concept-api/references/attribute_type.yml
  04-concept-api/references/concept.yml
  04-concept-api/references/entity.yml
  04-concept-api/references/relation.yml
  04-concept-api/references/role_type.yml
  04-concept-api/references/rule.yml
  04-concept-api/references/thing.yml
  04-concept-api/references/type.yml
  07-workbase/00-overview.md
  08-examples/03-phone-calls-migration-nodejs.md
  08-examples/05-phone-calls-queries.md
  WORKSPACE
  dependencies/vaticle/repositories.bzl
  test/example/nodejs/BUILD
  test/example/nodejs/PhoneCalls.template.js
  test/example/nodejs/SocialNetwork.template.js
  test/example/nodejs/package.json
  test/example/nodejs/yarn.lock
  test/example/python/BUILD
Labels: javascript, priority: medium, type: feature

#546 Replace .gql with .tql in quickstart
  00-general/04-quickstart.md
Labels: priority: medium, type: documentation
