Repository typedb/typedb-docs, pull requests merged in 2021-01, with the labels that each got.

#346 Update link to Graql intro document
  08-examples/05-phone-calls-queries.md
Labels: type: bug

#470 Update grabl automation yaml syntax
  .grabl/automation.yml
Labels: type: build

#472 Update Client Java docs
  00-general/04-quickstart.md
  03-client-api/01-java.md
  03-client-api/02-python.md
  03-client-api/03-nodejs.md
  07-workbase/00-overview.md
  08-examples/02-phone-calls-migration-java.md
  08-examples/05-phone-calls-queries.md
  09-schema/00-overview.md
  11-query/00-overview.md
  11-query/06-aggregate-query.md
  11-query/07-compute-query.md
  dependencies/graknlabs/repositories.bzl
  test/example/java/PhoneCallsTest.java
  test/example/java/SocialNetworkTest.java
  test/links/links_test.py
  test/query/templates/GraqlJavaTest.java
  test/query/templates/GraqlLangTest.java
Labels: priority: medium, type: documentation

#475 Client API 2.0
  03-client-api/00-overview.md
  03-client-api/02-python.md
  03-client-api/03-nodejs.md
  03-client-api/04-new-client.md
  03-client-api/references/answer.yml
  03-client-api/references/client.yml
  03-client-api/references/grakn.yml
  03-client-api/references/iterator.yml
  03-client-api/references/options.yml
  03-client-api/references/query_manager.yml
  03-client-api/references/session.yml
  03-client-api/references/stream.yml
  03-client-api/references/transaction.yml
  04-concept-api/02-type.md
  04-concept-api/04-thing.md
  04-concept-api/references/attribute.yml
  04-concept-api/references/attribute_type.yml
  04-concept-api/references/boolean_attribute_type.yml
  04-concept-api/references/concept.yml
  04-concept-api/references/concept_manager.yml
  04-concept-api/references/datetime_attribute_type.yml
  04-concept-api/references/double_attribute_type.yml
  04-concept-api/references/entity.yml
  04-concept-api/references/entity_type.yml
  04-concept-api/references/logic_manager.yml
  04-concept-api/references/long_attribute_type.yml
  04-concept-api/references/relation.yml
  04-concept-api/references/relation_type.yml
  04-concept-api/references/role.yml
  04-concept-api/references/role_type.yml
  04-concept-api/references/rule.yml
  04-concept-api/references/string_attribute_type.yml
  04-concept-api/references/thing.yml
  04-concept-api/references/thing_type.yml
  04-concept-api/references/type.yml
  09-schema/00-overview.md
  11-query/00-overview.md
  README.md
Labels: priority: high, type: documentation
