Repository typedb/typedb-docs, pull requests merged in 2021-06, with the labels that each got.

#532 Update Console, Client Java, Client Python, and Client NodeJS regarding authentication
  00-general/04-quickstart.md
  02-console/01-console.md
  03-client-api/01-java.md
  03-client-api/02-python.md
  03-client-api/03-nodejs.md
  03-client-api/references/client.yml
  03-client-api/references/typedb.yml
  08-examples/02-phone-calls-migration-java.md
  08-examples/05-phone-calls-queries.md
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  test/example/java/PhoneCallsTest.java
  test/example/java/SocialNetworkTest.java
  test/query/templates/TypeQLJavaTest.java
  test/query/templates/TypeQLLangTest.java
Labels: type: feature

#533 Add Vaticle logo
  images/layout/vaticle-logo.svg
Labels: priority: high, type: feature

#534 Update client node imports and add options to quickstart
  00-general/04-quickstart.md
  03-client-api/03-nodejs.md
  08-examples/03-phone-calls-migration-nodejs.md
  08-examples/05-phone-calls-queries.md
  test/example/java/PhoneCallsTest.java
  test/example/nodejs/PhoneCalls.template.js
  test/example/nodejs/SocialNetwork.template.js
  test/example/nodejs/package.json
  test/example/nodejs/yarn.lock
Labels: priority: medium, type: documentation

#535 TypeDB Console page typo
  02-console/01-console.md
Labels: type: bug
