Repository typedb/typedb-docs, pull requests merged in 2021-04, with the labels that each got.

#507 Fix client-python's Quickstart syntax and QueryManager's return types
  03-client-api/02-python.md
  03-client-api/references/query_manager.yml
Labels: priority: medium, type: bug

#510 Update Type.getLabel
  04-concept-api/references/role_type.yml
  04-concept-api/references/type.yml
Labels: priority: high, type: bug

#511 Add console scripting, database schema, and transaction options
  02-console/01-console.md
  03-client-api/02-python.md
  03-client-api/03-nodejs.md
  06-management/03-migration-and-backup.md
Labels: priority: medium, type: feature

#513 Update examples code snippets with correct imports
  03-client-api/03-nodejs.md
  08-examples/02-phone-calls-migration-java.md
  08-examples/03-phone-calls-migration-nodejs.md
  08-examples/04-phone-calls-migration-python.md
Labels: priority: high

#512 Make isInferred a Local Thing method
  00-general/04-quickstart.md
  03-client-api/03-nodejs.md
  04-concept-api/references/thing.yml
  08-examples/03-phone-calls-migration-nodejs.md
  08-examples/05-phone-calls-queries.md
  test/example/nodejs/PhoneCalls.template.js
  test/example/nodejs/SocialNetwork.template.js
Labels: priority: low, type: feature

#514 Document ACID guarantees
  06-management/02-acid.md
  06-management/03-users.md
  06-management/04-migration-and-backup.md
  11-query/04-delete-query.md
  views/sidebar.yml
Labels: priority: medium, type: documentation

#515 Update client compatibility tables
  02-console/01-console.md
  03-client-api/01-java.md
  03-client-api/02-python.md
  03-client-api/03-nodejs.md
  03-client-api/references/options.yml
  07-workbase/00-overview.md
Labels: priority: medium, type: documentation

#516 Add getRules to LogicManager API
  04-concept-api/references/logic_manager.yml
Labels: type: documentation, type: feature
