Repository typedb/typedb-docs, pull requests merged in 2022-01, with the labels that each got.

#583 Fix incorrectly named options
  03-client-api/references/options.yml
Labels: type: bug, priority: medium

#582 Infer and Explain only work in a read transaction
  03-client-api/references/options.yml
Labels: priority: medium, type: documentation

#585 documentation: fix for call relation example
  08-examples/01-phone-calls-schema.md
Labels: type: bug

#581 Add transaction timeout option documentation
  .grabl/automation.yml
  00-general/04-quickstart.md
  03-client-api/00-overview.md
  03-client-api/01-java.md
  03-client-api/references/options.yml
  08-examples/02-phone-calls-migration-java.md
  08-examples/05-phone-calls-queries.md
  09-schema/04-examples.md
  11-query/04-delete-query.md
  WORKSPACE
  dependencies/maven/artifacts.snapshot
  dependencies/vaticle/artifacts.bzl
  dependencies/vaticle/repositories.bzl
  test/example/java/PhoneCallsTest.java
  test/example/java/SocialNetworkTest.java
  test/example/nodejs/package.json
  test/example/nodejs/yarn.lock
  test/query/templates/TypeQLJavaTest.java
  test/query/templates/TypeQLLangTest.java
Labels: status: blocked, priority: high, type: documentation

#584 Rewrite migration and backup page
  06-management/04-migration-and-backup.md
Labels: priority: medium, type: documentation
