Repository typedb/typedb-docs, pull requests merged in 2022-07, with the labels that each got.

#603 Sync "Other Languages" content with TypeDB's README
  03-client-api/00-overview.md
  03-client-api/04-other-languages.md
Labels: type: bug, priority: medium, domain: client-api

#604 Describe how to set up Console to support UTF-8 characters
  02-console/01-console.md
Labels: type: feature, priority: medium, domain: console

#607 Examples docs
  00-general/04-quickstart.md
  08-examples/00-overview.md
  08-examples/00-phone-calls-overview.md
  09-schema/00-overview.md
Labels: priority: medium, type: documentation

#609 Change the studio quickstart guide to use phone_calls
  07-studio/00-overview.md
  07-studio/01-quickstart.md
  08-examples/05-phone-calls-queries.md
  09-schema/04-examples.md
  images/examples/phone_calls_query_1_studio.png
  images/examples/phone_calls_query_2_studio.png
  images/examples/phone_calls_query_3_studio.png
  images/examples/phone_calls_query_4_studio.png
  images/examples/phone_calls_query_5_studio.png
  images/studio/databases-interface-github-database.png
  images/studio/databases-interface-phone-calls-database.png
  images/studio/everything-visualisation.png
  images/studio/git-visualisation.png
  images/studio/phone-calls-visualisation.png
  images/studio/project-data-committed.png
  images/studio/project-data-pasted.png
  images/studio/project-data-query-run.png
  images/studio/project-interface-created-folder.png
  images/studio/project-new-file-2.png
  images/studio/project-new-file-query-run.png
  images/studio/project-new-file-with-schema.png
  images/studio/project-new-file.png
  images/studio/project-schema-committed.png
  images/studio/project-schema-pasted.png
  images/studio/project-schema-query-run.png
  images/studio/query-visualisation.png
  images/studio/studio-schema-committed.png
  views/sidebar.yml
Labels: type: bug, priority: high, type: documentation

#610 Update examples links
  08-examples/00-overview.md
Labels: priority: medium, type: documentation
