Repository typedb/typedb-docs, pull requests merged in 2022-12, with the labels that each got.

#635 Update user management documentation
  06-management/03-users.md
Labels: priority: high, type: documentation, domain: management

#636 Bump to 2.14.2
  03-client-api/01-java.md
  07-studio/00-overview.md
Labels: priority: high, type: documentation

#640 Update to mention TypeDB Cluster 2.14.1
  03-client-api/01-java.md
  07-studio/00-overview.md
Labels: priority: high, type: documentation

#638 gh-633 Fix 404 for phone_calls example dataset files
  08-examples/02-phone-calls-migration-java.md
  08-examples/03-phone-calls-migration-nodejs.md
  08-examples/04-phone-calls-migration-python.md
Labels: type: bug, type: documentation
