Repository typedb/typedb-docs, pull requests merged in 2025-04, with the labels that each got.

#922 Update comparisons page for like & contains
  typeql/modules/ROOT/pages/statements/comparisons.adoc
Labels: domain: query

#919 Update driver tutorials and pages to support TypeDB Driver 3.1 with the unified constructor
  code_test/runners/base_runner.py
  code_test/runners/rust_runner.py
  code_test/runners/typeql_runner.py
  drivers/modules/ROOT/pages/java/index.adoc
  drivers/modules/ROOT/pages/java/tutorial.adoc
  drivers/modules/ROOT/pages/python/index.adoc
  drivers/modules/ROOT/pages/python/tutorial.adoc
  drivers/modules/ROOT/pages/rust/index.adoc
  drivers/modules/ROOT/pages/rust/tutorial.adoc
  drivers/modules/ROOT/partials/tutorials/java/pom.xml
  drivers/modules/ROOT/partials/tutorials/java/src/main/java/org/example2/Main.java
  drivers/modules/ROOT/partials/tutorials/python/sample.py
  drivers/modules/ROOT/partials/tutorials/rust/Cargo.lock
  drivers/modules/ROOT/partials/tutorials/rust/Cargo.toml
  drivers/modules/ROOT/partials/tutorials/rust/src/main.rs
  home/modules/ROOT/pages/crash-course.adoc
  manual/modules/ROOT/pages/connect/CE.adoc
  manual/modules/ROOT/pages/connect/cloud.adoc
  manual/modules/ROOT/pages/connect/enterprise.adoc
  manual/modules/ROOT/pages/tools/studio.adoc
Labels: type: documentation, domain: client-api, domain: examples

#927 Document the put stage
  typeql/modules/ROOT/pages/pipelines/put.adoc
Labels: domain: query

#929 Add 3.1.0 as an available version for cloud
  manual/modules/ROOT/pages/cloud/api/index.adoc
  manual/modules/ROOT/pages/cloud/api/reference.adoc
Labels: priority: high, type: documentation

#930 HTTP Endpoint documentation
  drivers/modules/ROOT/pages/http/api-reference.adoc
  drivers/modules/ROOT/pages/http/index.adoc
  drivers/modules/ROOT/pages/index.adoc
  drivers/modules/ROOT/partials/nav.adoc
  drivers/modules/resources/partials/http-api/requests/post-users.json.adoc
  drivers/modules/resources/partials/http-api/requests/put-users.json.adoc
  drivers/modules/resources/partials/http-api/requests/query-concept-documents-example.json.adoc
  drivers/modules/resources/partials/http-api/requests/query-concept-rows-example.json.adoc
  drivers/modules/resources/partials/http-api/requests/query.json.adoc
  drivers/modules/resources/partials/http-api/requests/signin.json.adoc
  drivers/modules/resources/partials/http-api/requests/transactions-open.json.adoc
  drivers/modules/resources/partials/http-api/requests/transactions-query-concept-documents-example.json.adoc
  drivers/modules/resources/partials/http-api/requests/transactions-query-concept-rows-example.json.adoc
  drivers/modules/resources/partials/http-api/requests/transactions-query.json.adoc
  drivers/modules/resources/partials/http-api/responses/details.adoc
  drivers/modules/resources/partials/http-api/responses/error.json.adoc
  drivers/modules/resources/partials/http-api/responses/get-database.json.adoc
  drivers/modules/resources/partials/http-api/responses/get-databases.json.adoc
  drivers/modules/resources/partials/http-api/responses/get-user.json.adoc
  drivers/modules/resources/partials/http-api/responses/get-users.json.adoc
  drivers/modules/resources/partials/http-api/responses/query-concept-documents-example.json.adoc
  drivers/modules/resources/partials/http-api/responses/query-concept-rows-example.json.adoc
  drivers/modules/resources/partials/http-api/responses/query.json.adoc
  drivers/modules/resources/partials/http-api/responses/signin.json.adoc
  drivers/modules/resources/partials/http-api/responses/transaction.json.adoc
  manual/modules/ROOT/pages/CRUD/updating.adoc
  manual/modules/ROOT/pages/configure/server.adoc
  manual/modules/ROOT/pages/connect/CE.adoc
  manual/modules/ROOT/pages/connect/cloud.adoc
  manual/modules/ROOT/pages/connect/enterprise.adoc
  manual/modules/ROOT/pages/databases/creating.adoc
  manual/modules/ROOT/pages/databases/deleting.adoc
  manual/modules/ROOT/pages/queries/answers.adoc
  manual/modules/ROOT/pages/queries/transactions.adoc
  manual/modules/ROOT/pages/tools/console.adoc
  manual/modules/ROOT/pages/tools/drivers.adoc
  manual/modules/ROOT/pages/users/creating.adoc
  manual/modules/ROOT/pages/users/deleting.adoc
  manual/modules/ROOT/pages/users/listing.adoc
  manual/modules/ROOT/pages/users/passwords.adoc
Labels: domain: client-api

#932 Update download links for 'latest' version to use cloudsmith's 'latest' tag
  manual/modules/resources/partials/typedb-all-latest-links.adoc
  manual/modules/resources/partials/typedb-all-latest-version.adoc
  manual/modules/resources/partials/typedb-console-latest-links.adoc
  manual/modules/resources/partials/typedb-console-latest-version.adoc
  manual/modules/resources/partials/typedb-studio-latest-links.adoc
  manual/modules/resources/partials/typedb-studio-latest-version.adoc
Labels: type: documentation

#931 Update transaction and query options specifications for GRPC and HTTP
  drivers/modules/ROOT/pages/http/api-reference.adoc
  drivers/modules/ROOT/pages/http/index.adoc
  manual/modules/ROOT/pages/migration/2_to_3.adoc
  manual/modules/ROOT/pages/queries/transactions.adoc
  manual/modules/resources/partials/options-descriptions/query.adoc
  manual/modules/resources/partials/options-descriptions/transaction.adoc
Labels: priority: high, domain: client-api
